
add_newline = false

[cmd_duration]
min_time = 1

[character]
use_symbol_for_status = true  # Show "âœ–" when the command faild

[hostname]
ssh_only = false
prefix = "â®"
suffix = "â¯"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = true

[directory]
truncation_length = 10
truncate_to_repo = false

[time]
disabled = false
style = "black"
format = "ğŸ•™ %T"

[battery]
disabled = false
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 20
style = "bold red"

[jobs]
symbol = "âœ¦ "
threshold = 1

[memory_usage]
show_percentage = true
show_swap = true
threshold = 95
style = "bold dimmed green"
disabled = false

[git_branch]
style = "bold yellow"

[git_status]
conflicted = "âš”ï¸ "
#ahead = "ğŸï¸ ğŸ’¨ "
#behind = "ğŸ¢ "
#diverged = "ğŸ”± "
#untracked = "ğŸ›¤ï¸ "
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
modified_count.enabled = true
#staged = "ğŸ—ƒï¸ "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
#renamed = "ğŸ‘…"
renamed = "ğŸ“› "
deleted = "ğŸ—‘"
style = "black"
show_sync_count = true
#prefix = "with "
#suffix = ""

[git_commit]
commit_hash_length = 7
only_detached = false
prefix = "(commit "
